apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: web
        image: 734217158330.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        ports:
        - containerPort: 5000
