apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: employees
spec:
  imagePullSecrets:
  - name: ecr-registry-secret
  containers:
  - name: web
    image: 734217158330.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: DBHOST
      value: mysql-service
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: root
    - name: DBPWD
      value: rootpass
    ports:
    - containerPort: 8080
