# Exposing Web app via Node Port which is 30000

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: employees
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
